export const MENU = [
  {
    id: 1,
    name: 'THE BEAST SMASH',
    tag: '#1 Most Loved',
    desc: 'Double smash patty, aged cheddar, sriracha aioli, toasted brioche bun',
    protein: 52,
    kcal: 680,
    price: '£12.50',
    image: '/food-card-1.jpeg',
    chef: 'Chef Marcus Webb',
    kitchen: 'IRONPLATE Kitchen',
    quote: 'Every patty is hand-smashed to order. The crust is everything.',
    rating: 4.9,
    likes: 214,
  },
  {
    id: 2,
    name: 'IRON STACK',
    tag: 'Triple Stacked',
    desc: 'Three smash patties, egg crown, black bun, truffle mayo',
    protein: 61,
    kcal: 720,
    price: '£15.90',
    image: '/food-card-2.jpeg',
    chef: 'Chef Marcus Webb',
    kitchen: 'IRONPLATE Kitchen',
    quote: 'Three patties. One mission. Maximum protein, zero regrets.',
    rating: 4.8,
    likes: 189,
  },
  {
    id: 3,
    name: 'POWERHOUSE BOWL',
    tag: 'Post-Workout Fuel',
    desc: 'Grilled chicken thigh, jasmine rice, chimichurri, pickled slaw',
    protein: 48,
    kcal: 580,
    price: '£11.50',
    image: '/food-card-3.jpeg',
    chef: 'Chef Sasha Okafor',
    kitchen: 'IRONPLATE Kitchen',
    quote: 'Chimichurri from scratch, every single day. No shortcuts.',
    rating: 4.7,
    likes: 143,
  },
  {
    id: 4,
    name: 'MIDNIGHT BURN',
    tag: 'Late Night Special',
    desc: 'Charred black bun, ghost pepper sauce, pickled onion, crispy patty',
    protein: 47,
    kcal: 640,
    price: '£13.90',
    image: '/food-card-4.jpeg',
    chef: 'Chef Marcus Webb',
    kitchen: 'IRONPLATE Kitchen',
    quote: 'Ghost pepper heat that hits after the first bite. You have been warned.',
    rating: 4.8,
    likes: 176,
  },
]

export const REVIEWS = [
  {
    initials: 'JH',
    name: 'Jamie Holloway',
    text: '"The Beast Smash is genuinely the best burger in East London. 52g of protein and it actually tastes unreal. I order after every leg day."',
  },
  {
    initials: 'PO',
    name: 'Priya Osei',
    text: '"Finally a place in Shoreditch that takes macros seriously without sacrificing flavour. The Powerhouse Bowl is my post-training ritual."',
  },
  {
    initials: 'TM',
    name: 'Tom McAllister',
    text: '"Iron Stack is dangerous. Three patties and I still hit my protein goals for the day. Best thing to happen to Bethnal Green. Full stop."',
  },
]

export const INGREDIENTS = [
  { src: '/ingredients/bun-bottom.png', label: 'Toasted Brioche Base', protein: 2,  color: '#B8860B', height: 40 },
  { src: '/ingredients/pickle.png',     label: 'House Pickles',         protein: 0,  color: '#556B2F', height: 20 },
  { src: '/ingredients/onion.png',      label: 'Caramelised Onion',     protein: 1,  color: '#8B4513', height: 25 },
  { src: '/ingredients/tomato.png',     label: 'Heirloom Tomato',       protein: 1,  color: '#8B1A1A', height: 28 },
  { src: '/ingredients/lettuce.png',    label: 'Butter Lettuce',        protein: 1,  color: '#2E5E2E', height: 30 },
  { src: '/ingredients/sauce.png',      label: 'Sriracha Aioli',        protein: 0,  color: '#CC3300', height: 18 },
  { src: '/ingredients/cheese.png',     label: 'Aged Cheddar',          protein: 7,  color: '#D4870A', height: 22 },
  { src: '/ingredients/patty-2.png',    label: 'Smash Patty #2',        protein: 19, color: '#3D1C0A', height: 55 },
  { src: '/ingredients/patty-1.png',    label: 'Smash Patty #1',        protein: 19, color: '#2D1205', height: 55 },
  { src: '/ingredients/bun-top.png',    label: 'Sesame Crown',          protein: 2,  color: '#A0700A', height: 65 },
]
